version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: "wednesday"
    open-pull-requests-limit: 5
    rebase-strategy: "disabled"
    commit-message:
      prefix: build
      include: scope

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: "wednesday"
    open-pull-requests-limit: 5
    rebase-strategy: "disabled"
    commit-message:
      prefix: build
      include: scope
